const { initializeApp, applicationDefault } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
initializeApp({ credential: applicationDefault(), projectId:'sentinel-ci-c7592' });
const db=getFirestore();
const NIVEAUX=['2nde','1ere','Tle'];
const MATIERES=['arts','math','pc','svt','franc','angl','hg','philo','eps','info','ecm'];
const D={
math:['Mathématiques','Identifier les données, choisir la propriété ou formule, résoudre étape par étape, vérifier et conclure.','définition, propriété, formule, calcul, raisonnement'],
pc:['Physique-Chimie','Identifier le système et les grandeurs, convertir les unités, choisir la loi, calculer avec unité et interpréter.','grandeur, unité, mesure, loi, transformation'],
svt:['SVT','Présenter le problème, exploiter les observations, relier faits et connaissances, expliquer et conclure.','observation, organisme, cellule, mécanisme, environnement'],
franc:['Français','Comprendre le sujet, relever les indices, organiser les idées, rédiger et relire.','texte, argument, narration, analyse, langue'],
angl:['Anglais','Understand the context, identify key words, choose the correct structure, produce and check a clear sentence.','vocabulary, grammar, tense, communication'],
hg:['Histoire-Géographie','Identifier le sujet, situer dans le temps ou l’espace, présenter acteurs et faits, analyser causes et conséquences.','repère, acteur, espace, cause, conséquence'],
philo:['Philosophie','Définir les termes, dégager le problème, construire des arguments, donner des exemples, discuter et conclure.','notion, concept, problème, argument, exemple'],
arts:['Arts plastiques','Observer, identifier l’intention, expérimenter, réaliser, expliquer et analyser les choix plastiques.','forme, couleur, matière, espace, image'],
eps:['EPS','Définir l’objectif, s’échauffer, réaliser avec une technique adaptée, mesurer l’effort et récupérer.','effort, sécurité, technique, performance, récupération'],
info:['Informatique','Définir le problème, le décomposer, représenter les données, construire, tester et corriger.','donnée, algorithme, programme, réseau, sécurité'],
ecm:['Éducation civique et morale','Identifier la situation, rappeler le principe, distinguer droits et devoirs, examiner les conséquences et agir avec responsabilité.','citoyen, droit, devoir, règle, responsabilité']
};
function d(id){return D[id]||D.ecm;}
function cours(id,n,t){const x=d(id);return '# '+t+'\n\n## Niveau '+n+'\n\n## Objectifs\nMaîtriser les notions essentielles de « '+t+' », savoir les expliquer, les appliquer et justifier une réponse.\n\n## Introduction\n'+x[0]+' : ce chapitre est étudié à partir d’une situation, de notions précises, d’exemples et d’applications.\n\n## Notions essentielles\nMots-clés : **'+x[2]+'**. Les définitions doivent être apprises puis reformulées avec ses propres mots.\n\n## Comprendre\nCommencer par identifier le problème ou la consigne. Repérer les informations utiles, relier les notions entre elles et construire une explication logique. Une connaissance est réellement maîtrisée lorsqu’elle peut être réutilisée dans une situation nouvelle.\n\n## Exemple guidé\nFace à une situation liée à « '+t+' », identifier ce qui est demandé, sélectionner les connaissances pertinentes, les appliquer dans l’ordre et terminer par une conclusion répondant directement à la question.\n\n## Méthode\n'+x[1]+'\n\n## Erreurs à éviter\n- réciter sans expliquer ;\n- oublier une justification ou une unité lorsqu’elle est nécessaire ;\n- confondre exemple et preuve ;\n- répondre sans organiser les idées ;\n- ne pas relire.\n\n## À retenir\nLes définitions, mots-clés, relations essentielles et méthodes doivent pouvoir être expliqués sans regarder le cours.\n';}
function exercices(id,n,t){const x=d(id);return '# Exercices — '+t+'\n\n## Exercice 1 — Restitution\nDéfinis deux notions du chapitre, donne trois mots-clés et résume l’idée principale en cinq lignes.\n\n### Correction\nLes définitions doivent être exactes, les mots-clés pertinents et la synthèse organisée.\n\n## Exercice 2 — Application\nTraite une situation concrète portant sur « '+t+' ». Identifie les informations utiles, applique la méthode et justifie chaque étape.\n\n### Correction\n1. Identifier la demande. 2. Sélectionner les informations utiles. 3. Mobiliser la notion. 4. Justifier. 5. Conclure.\n\n## Exercice 3 — Raisonnement\nExplique le lien entre deux éléments importants du chapitre et donne un exemple.\n\n### Correction\nLe lien doit être formulé avec un raisonnement logique et l’exemple doit correspondre à la notion.\n\n## Exercice 4 — Transfert\nImagine une situation nouvelle dans laquelle le chapitre est utile et rédige une réponse complète.\n\n### Correction\nLa réponse doit montrer que la connaissance est transférée à une situation différente.\n\n## Méthode\n'+x[1]+'\n';}
function renforcement(id,n,t){return '# Renforcement — '+t+'\n\n## Situation-problème\nUn élève connaît les définitions mais ne sait pas les utiliser dans une situation nouvelle.\n\n### Travail demandé\n1. Reformule la notion centrale.\n2. Identifie l’information déterminante.\n3. Explique le raisonnement étape par étape.\n4. Donne un exemple.\n5. Indique une erreur à éviter.\n\n## Correction attendue\nUne bonne réponse part du sujet, mobilise la connaissance pertinente, justifie les étapes et conclut clairement.\n\n## Défi\nExplique le chapitre à un camarade en trois minutes sans lire le cours.\n';}
function quiz(t){return [1,2,3,4,5,6].map(function(i){var q=[['La première étape est-elle de comprendre la consigne ?',['Oui','Non'],0,'Oui, la consigne précise ce qui est attendu.'],['Une définition doit-elle être précise ?',['Oui','Non'],0,'Oui, la précision évite les confusions.'],['Une affirmation sans justification suffit-elle quand le raisonnement est demandé ?',['Oui','Non'],1,'Non, il faut expliquer et justifier.'],['Faut-il vérifier sa réponse ?',['Oui','Non'],0,'Oui, la relecture permet de corriger les erreurs.'],['Un exemple doit-il correspondre à la notion ?',['Oui','Non'],0,'Oui, il doit illustrer correctement la notion.'],['Peut-on réutiliser une connaissance dans une situation nouvelle ?',['Oui','Non'],0,'Oui, le transfert montre la compréhension.']][i-1];return {id:'q'+i,type:'qcm',enonce:q[0]+' — '+t,choix:q[1],bonnesReponses:[q[2]],reponseAttendue:'',explication:q[3],points:1};});}
function fiche(id,n,t){var x=d(id);return '# Fiche de révision — '+t+'\n\n## Niveau '+n+'\n\n### Mots-clés\n**'+x[2]+'**\n\n### Je dois savoir\n- définir les notions centrales ;\n- expliquer l’idée ou le mécanisme ;\n- reconnaître une situation d’application ;\n- traiter un exercice ;\n- justifier et conclure.\n\n### Méthode express\n'+x[1]+'\n\n### Auto-évaluation\n☐ Je peux expliquer le chapitre sans lire.\n☐ Je peux donner un exemple.\n☐ Je peux traiter un exercice.\n☐ Je peux expliquer une erreur à éviter.\n☐ Je peux répondre à une question nouvelle.\n';}
async function main(){const q=await db.collection('ca_chapitres').where('anneeScolaire','==','2026-2027').where('niveau','in',NIVEAUX).limit(1000).get();let total=0,chap=0;for(const z of q.docs){const c={id:z.id,...z.data()};if(MATIERES.indexOf(String(c.matiereId))<0)continue;const types=[['cours','Cours complet — '+c.titre,cours(c.matiereId,c.niveau,c.titre),[],40],['exercices','Exercices et corrections — '+c.titre,exercices(c.matiereId,c.niveau,c.titre),[],35],['renforcement','Renforcement — '+c.titre,renforcement(c.matiereId,c.niveau,c.titre),[],25],['quiz','QCM — '+c.titre,'QCM de vérification des acquis.',quiz(c.titre),10],['revision','Fiche de révision — '+c.titre,fiche(c.matiereId,c.niveau,c.titre),[],15]];for(let i=0;i<types.length;i++){const a=types[i];const old=await db.collection('ca_ressources').where('chapitreId','==',c.id).where('type','==',a[0]).limit(1).get();const ref=old.empty?db.collection('ca_ressources').doc(c.id+'_secondcycle_'+a[0]):old.docs[0].ref;const data={type:a[0],titre:a[1],ordre:i+1,chapitreId:c.id,niveau:c.niveau,matiereId:c.matiereId,ecoleId:'',contenu:a[2],imagesUrls:[],pdfUrl:'',videoYoutubeId:'',enonce:'',solution:'',difficulte:a[0]==='quiz'?2:1,ressourceLieeId:'',questions:a[3],dureeMinutes:a[4],examen:'',annee:2026,serie:'',actif:true,ressourceNationale:true,auteur:'Sentinel CI — enrichissement pédagogique',dateCreation:old.empty?FieldValue.serverTimestamp():(old.docs[0].data().dateCreation||FieldValue.serverTimestamp()),dateMaj:FieldValue.serverTimestamp()};await ref.set(data,{merge:true});total++;}chap++;}await db.collection('ca_parametres').doc('version').set({version:FieldValue.increment(1),dateMaj:FieldValue.serverTimestamp()},{merge:true});console.log(JSON.stringify({ok:true,chapitresTraites:chap,ressourcesEcrites:total},null,2));}
main().catch(e=>{console.error(e);process.exit(1);});