const { initializeApp, applicationDefault } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
initializeApp({ credential: applicationDefault(), projectId:'sentinel-ci-c7592' });
const db=getFirestore();
const SOURCES=[];
const CHAPTERS=[
 {id:'6e_math_ch11',title:'Figures symétriques par rapport à un point',source:SOURCES[0]},
 {id:'6e_math_ch12',title:'Statistique',source:SOURCES[1]},
 {id:'6e_math_ch13',title:'Parallélogramme',source:SOURCES[2]},
];
function section(source,startRe,endRe){const lines=source.split('\n');const s=lines.findIndex(l=>startRe.test(l));if(s<0)return '';let e=lines.length;for(let i=s+1;i<lines.length;i++){if(endRe.test(lines[i])){e=i;break;}}return lines.slice(s+1,e).join('\n').trim();}
function parseQcm(block){const out=[];const chunks=block.split(/(?=### Question \d+|\*\*\d+\.\*\*)/g).filter(Boolean);for(const chunk of chunks){const m=chunk.match(/(?:### Question |\*\*)(\d+)/);if(!m)continue;const q=chunk.replace(/^(?:### Question |\*\*)(\d+)(?:\*\*)?\s*/,'').split(/\n\s*(?=A\.|B\.|C\.|D\.)/)[0].trim();const options=[];for(const o of chunk.matchAll(/(?:^|\n)\s*([ABCD])\.\s*(.+)/g))options.push({label:o[1],text:o[2].trim()});if(options.length>=2)out.push({questionNumber:Number(m[1]),question:q,options});}return out;}
function extract(source){const course=section(source,/^# 📖 2\. COURS$/,/^# ✏️ 3\. EXERCICES/);const exercises=section(source,/^# ✏️ 3\. EXERCICES/,/^# 🔵 4\. RENFORCEMENT/);const reinforcement=section(source,/^# 🔵 4\. RENFORCEMENT/,/^# 🔴 5\. PROBLÈMES/);const problems=section(source,/^# 🔴 5\. PROBLÈMES/,/^# 📝 6\. QCM/);const qcm=section(source,/^# 📝 6\. QCM/,/^# ✅ 7\. CORRECTION/);const correction=section(source,/^# ✅ 7\. CORRECTION/,/^# 📋 8\. FICHE MÉMO/);const revision=section(source,/^# 📋 8\. FICHE MÉMO/,/^# 🎮 9\. QUIZ/);const quiz=section(source,/^# 🎮 9\. QUIZ/,/^# 🏆 10\. DÉFI FINAL/);const challenge=section(source,/^# 🏆 10\. DÉFI FINAL/,/^# .*BILAN/);const bilan=section(source,/^# .*BILAN/,$/);return {course,exercises,reinforcement,problems,qcm,correction,revision,quiz,challenge,bilan,questions:parseQcm(qcm)};}
function res(ch,type,title,content,extra={}){return {chapitreId:ch,matiereId:'math',type,titre:title,contenu:content,actif:false,ressourceLieeId:'',...extra,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};}
async function del(refs){let n=0;for(let i=0;i<refs.length;i+=450){const b=db.batch();for(const r of refs.slice(i,i+450))b.delete(r);await b.commit();n+=Math.min(450,refs.length-i);}return n;}
async function main(){let oldResourcesDeleted=0,resourcesCreated=0;for(const ch of CHAPTERS){const old=await db.collection('ca_ressources').where('chapitreId','==',ch.id).get();oldResourcesDeleted+=await del(old.docs.map(d=>d.ref));const d=extract(ch.source);const rs=[res(ch.id,'cours',`Cours — ${ch.title}`,d.course),res(ch.id,'exercices',`Exercices — ${ch.title}`,d.exercises+'\n\n# Problèmes\n\n'+d.problems),res(ch.id,'renforcement',`Renforcement — ${ch.title}`,d.reinforcement),res(ch.id,'quiz',`QCM / Quiz — ${ch.title}`,d.qcm+'\n\n# Correction expliquée\n\n'+d.correction+'\n\n# Quiz\n\n'+d.quiz+'\n\n# Défi final\n\n'+d.challenge,{questions:d.questions}),res(ch.id,'revision',`Fiche de révision — ${ch.title}`,d.revision+'\n\n# Bilan\n\n'+d.bilan)];const b=db.batch();for(const r of rs)b.set(db.collection('ca_ressources').doc(),r);await b.commit();resourcesCreated+=rs.length;console.log(`REPLACED ${ch.id}: old=${old.size}, new=5, draft-only`);}await db.collection('ca_parametres').doc('version').set({math6eUserLot:'MATH_6E_LOT_CH11_CH13_REPLACEMENT',mode:'full_replacement',chaptersProcessed:CHAPTERS.map(x=>x.id),oldResourcesDeleted,resourcesCreated,publication:'draft_only',updatedAt:FieldValue.serverTimestamp()},{merge:true});console.log(JSON.stringify({mode:'full_replacement',chaptersProcessed:3,oldResourcesDeleted,resourcesCreated,expectedResources:15,publication:'draft_only'},null,2));}
main().catch(e=>{console.error(e);process.exit(1);});