const { initializeApp, applicationDefault } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
initializeApp({ credential: applicationDefault(), projectId:'sentinel-ci-c7592' });
const db=getFirestore();

const NIVEAUX=['2nde','1ere','Tle'];
const MATIERES=['arts','math','pc','svt','franc','angl','hg','philo','eps','info','ecm'];

const DOMAINE={
math:{nom:'Mathématiques',base:'Le raisonnement mathématique relie définitions, propriétés, calculs et démonstrations. Une solution doit être lisible, justifiée et vérifiée.'},
pc:{nom:'Physique-Chimie',base:'La démarche scientifique part d’un phénomène ou d’une situation, identifie les grandeurs pertinentes, choisit une loi ou un modèle, effectue les calculs avec unités puis interprète le résultat.'},
svt:{nom:'SVT',base:'La démarche en SVT s’appuie sur des observations, des résultats expérimentaux ou des documents. Il faut distinguer faits, interprétations et connaissances afin de construire une explication argumentée.'},
franc:{nom:'Français',base:'L’étude du français associe compréhension des textes, analyse des procédés, maîtrise de la langue et production écrite. Une interprétation doit être appuyée par des indices précis du texte.'},
angl:{nom:'Anglais',base:'Learning English requires understanding meaning in context, controlling grammar and vocabulary, and producing a message suited to the situation and audience.'},
hg:{nom:'Histoire-Géographie',base:'L’analyse historique et géographique situe les faits, identifie les acteurs et les espaces, confronte les informations et explique les relations de cause, de conséquence et d’organisation territoriale.'},
philo:{nom:'Philosophie',base:'La réflexion philosophique commence par la définition des termes, transforme une question en problème, confronte des arguments et construit une réponse justifiée. Une thèse doit être distinguée d’un exemple.'},
arts:{nom:'Arts plastiques',base:'La pratique artistique articule intention, expérimentation, choix plastiques et analyse. Une production se comprend par ses formes, couleurs, matériaux, espace, cadrage et contexte.'},
eps:{nom:'EPS',base:'La pratique physique associe apprentissage technique, gestion de l’effort, sécurité, observation de la performance et capacité à ajuster son action.'},
info:{nom:'Informatique',base:'Une démarche informatique décompose un problème, représente les données, conçoit une solution, la teste puis corrige les erreurs. La sécurité et l’éthique font partie de la compétence numérique.'},
ecm:{nom:'Éducation civique et morale',base:'L’éducation civique relie valeurs, droits, devoirs, institutions et situations concrètes. Une réponse solide distingue les principes, les règles applicables, les responsabilités et les conséquences.'}
};

function specific(id,t){
 const s=t.toLowerCase();
 if(id==='math'){
  if(/dérivation|variations/.test(s)) return ['La dérivée mesure localement la variation d’une fonction et permet d’étudier son sens de variation. Si f est dérivable, le signe de f’ commande les variations : f’ positive signifie que f croît sur l’intervalle considéré, f’ négative qu’elle décroît. Les zéros de f’ sont des valeurs critiques à examiner dans le tableau de variations.','Pour f(x)=x²-4x+1, f’(x)=2x-4. Elle est négative avant 2 et positive après 2 : la fonction décroît puis croît et possède un minimum en x=2.','Domaine → dérivée → factorisation si nécessaire → tableau de signe de f’ → variations → valeurs remarquables.'];
  if(/limites|continuité/.test(s)) return ['Une limite décrit le comportement d’une fonction lorsque la variable se rapproche d’une valeur ou devient très grande. La continuité en a signifie que f(x) tend vers f(a) lorsque x tend vers a. Les formes indéterminées exigent une transformation algébrique avant de conclure.','Pour (x²-1)/(x-1), la factorisation donne x+1 pour x différent de 1 ; la limite en 1 vaut donc 2, même si l’expression initiale n’est pas définie en 1.','Identifier la situation, simplifier si possible, choisir la propriété de limite puis vérifier le résultat avec le comportement attendu.'];
  if(/probabilit/.test(s)) return ['Une probabilité quantifie la possibilité d’un événement. Dans un univers fini équiprobable, P(A)=nombre de cas favorables/nombre de cas possibles. On utilise aussi complément, union, intersection et probabilités conditionnelles selon la situation.','Pour un dé équilibré, P(obtenir un nombre pair)=3/6=1/2. L’événement contraire a aussi une probabilité qui complète à 1.','Définir l’univers, l’événement, les informations disponibles, puis choisir la formule adaptée et interpréter le résultat.'];
  if(/logarithme/.test(s)) return ['La fonction logarithme népérien est définie sur ]0;+∞[, vérifie ln(ab)=ln(a)+ln(b) et possède pour dérivée 1/x. Elle transforme une relation multiplicative en relation additive et intervient dans les équations où l’inconnue apparaît dans un produit ou un exposant.','Résoudre ln(x)=3 donne x=e³. Résoudre ln(x)+ln(2)=ln(10) revient à ln(2x)=ln(10), donc x=5.','Toujours vérifier la positivité des arguments, appliquer les propriétés avec leurs conditions puis contrôler la solution dans l’équation initiale.'];
  if(/exponentielle/.test(s)) return ['La fonction exponentielle est strictement positive, vérifie exp(a+b)=exp(a)exp(b) et est sa propre dérivée. Elle modélise notamment des évolutions multiplicatives continues. Le logarithme permet de résoudre les équations où l’inconnue est dans l’exposant.','e^x=7 équivaut à x=ln(7). Pour une croissance continue, la valeur après un temps t peut prendre la forme A e^(kt).','Mettre l’équation sous une forme comparable, utiliser les propriétés de l’exponentielle ou appliquer ln, puis vérifier le domaine et l’ordre de grandeur.'];
  return ['Le chapitre développe des notions qui doivent être reliées à des propriétés et à des procédures de résolution. En mathématiques, le calcul n’est pas séparé du raisonnement : chaque transformation doit être autorisée par une propriété connue et chaque résultat doit être interprété.','Construis un exemple numérique simple, puis explique pourquoi chaque étape est valide avant de généraliser la méthode.','Données → définition ou propriété → calcul/raisonnement → justification → vérification → conclusion.'];
 }
 if(id==='pc'){
  if(/newton|dynamique/.test(s)) return ['La dynamique relie mouvement et actions mécaniques. Dans un référentiel donné, la deuxième loi de Newton s’écrit somme des forces = m a. La relation est vectorielle : direction et sens de l’accélération comptent autant que sa valeur.','Pour un objet de masse 2 kg soumis à une force résultante horizontale de 6 N, l’accélération vaut 3 m·s⁻² dans la direction de la résultante.','Choisir le système et le référentiel, faire le bilan des forces, projeter la relation sur les axes utiles, calculer puis interpréter le signe et l’unité.'];
  if(/travail|énergie/.test(s)) return ['Le travail d’une force mesure un transfert d’énergie lié au déplacement. Pour une force constante parallèle au déplacement, W=F×d. L’énergie cinétique dépend de la masse et de la vitesse : Ec=1/2 mv². L’analyse énergétique consiste à identifier les transferts et les éventuelles dissipations.','Un objet accélère : son énergie cinétique augmente. Si les frottements sont importants, une partie de l’énergie mécanique est transformée en énergie thermique.','Définir le système, identifier les formes d’énergie, écrire les relations adaptées, choisir les signes et vérifier la conservation ou le bilan énergétique.'];
  if(/acide|base/.test(s)) return ['Une solution acide contient une concentration en ions oxonium supérieure à celle d’une solution neutre ; le pH permet de caractériser son acidité. Une base possède des propriétés opposées. La dilution diminue la concentration et modifie le pH sans créer une nouvelle espèce par elle-même.','Une solution de pH 3 est plus acide qu’une solution de pH 5. Une dilution d’une solution acide tend à rapprocher son pH de 7.','Identifier la solution, relever les données, relier pH et acidité, puis distinguer concentration, dilution et réaction chimique.'];
  if(/électricité|dipôle|ohm/.test(s)) return ['Dans un circuit, l’intensité et la tension décrivent des grandeurs différentes. Pour un conducteur ohmique, la loi d’Ohm s’écrit U=RI. La puissance électrique d’un dipôle peut s’écrire P=UI. Les mesures doivent respecter les branchements et les unités.','Pour R=100 Ω et I=0,20 A, U=20 V. Si la tension et le courant sont connus, P=UI permet de calculer la puissance reçue ou fournie selon la convention choisie.','Faire le schéma, identifier les grandeurs, convertir les unités, choisir la loi puis vérifier l’unité et l’ordre de grandeur.'];
  if(/radioactivité/.test(s)) return ['La radioactivité correspond à une transformation spontanée de noyaux instables avec émission de rayonnements. La période radioactive est la durée au bout de laquelle la moitié des noyaux radioactifs initiaux se sont désintégrés. Elle permet de prévoir une diminution statistique du nombre de noyaux.','Après une période, il reste 50 % de l’activité initiale ; après deux périodes, 25 %. Cette évolution est exponentielle et ne signifie pas qu’un noyau individuel se désintègre à un instant prévisible.','Identifier la période, exprimer le nombre de périodes écoulées et utiliser la loi de décroissance avant d’interpréter le résultat.'];
  return [DOMAINE.pc.base,'Construis un bilan à partir d’un phénomène concret et relie chaque grandeur à son unité et à la loi qui permet de l’exploiter.','Système → données → loi → calcul → unité → interprétation.'];
 }
 if(id==='svt'){
  if(/génétique|hérédit/.test(s)) return ['Un caractère héréditaire dépend d’informations génétiques transmises lors de la reproduction. Un gène correspond à une portion d’ADN portant une information ; des versions différentes d’un même gène sont des allèles. Le génotype contribue au phénotype avec l’influence de l’environnement selon le caractère étudié.','Pour un caractère déterminé par deux allèles, un individu reçoit une copie de chaque parent. Les croisements permettent de prévoir des proportions théoriques, à condition de respecter les hypothèses du modèle.','Définir caractère, gène, allèle et génotype, représenter les gamètes puis construire le croisement avant de calculer les proportions.'];
  if(/immun|défense/.test(s)) return ['L’organisme possède des défenses innées et adaptatives. La réponse immunitaire implique notamment des cellules capables de reconnaître des éléments étrangers et de produire une réponse spécifique. La mémoire immunitaire explique l’efficacité accrue d’une réponse lors d’un contact ultérieur avec le même antigène.','Après vaccination, l’organisme peut conserver des cellules mémoires qui permettent une réponse plus rapide lors d’une nouvelle exposition.','Distinguer agent, antigène, réponse, anticorps et mémoire, puis relier les observations expérimentales au mécanisme proposé.'];
  if(/écosystème|biodiversité/.test(s)) return ['Un écosystème associe un milieu et les êtres vivants qui y interagissent. Les relations alimentaires, la compétition, la prédation et les échanges de matière et d’énergie contribuent à son fonctionnement. La biodiversité se décrit à plusieurs niveaux : diversité des écosystèmes, des espèces et des variations au sein d’une espèce.','Dans une chaîne alimentaire, une diminution importante d’une espèce peut modifier les effectifs d’autres populations. L’effet dépend des relations présentes dans le réseau.','Identifier les organismes, les relations et les flux, puis construire une représentation avant d’expliquer les conséquences d’une perturbation.'];
  if(/évolution/.test(s)) return ['L’évolution décrit les changements des populations au cours des générations. La diversité génétique fournit une matière sur laquelle peuvent agir différents mécanismes, notamment la sélection naturelle. Une adaptation correspond à un caractère qui augmente la survie ou la reproduction dans un contexte donné ; elle n’est pas une transformation volontaire d’un individu.','Si une variation héréditaire améliore la survie dans un milieu donné, les individus qui la portent peuvent laisser davantage de descendants, ce qui peut modifier la fréquence du caractère au fil des générations.','Distinguer variation, hérédité, sélection et adaptation, puis raisonner à l’échelle des populations et des générations.'];
  return [DOMAINE.svt.base,'À partir d’un document ou d’une observation, formule une hypothèse puis confronte-la aux données avant de conclure.','Observations → faits → connaissances → raisonnement → conclusion.'];
 }
 if(id==='franc'){
  if(/argumentation|persuasion|essai/.test(s)) return ['Argumenter consiste à soutenir une thèse au moyen de raisons organisées. Un texte argumentatif peut utiliser exemples, données, analogies, réfutations et connecteurs logiques. Convaincre s’appuie notamment sur la solidité du raisonnement ; persuader mobilise davantage les émotions et l’implication du lecteur.','Pour défendre l’idée que la lecture développe l’esprit critique, il faut annoncer une thèse, fournir des arguments distincts, les illustrer et répondre à une objection possible.','Définir le sujet, formuler la thèse, classer les arguments, prévoir une objection, rédiger avec des connecteurs et conclure sans répéter mécaniquement l’introduction.'];
  if(/roman|récit|narration/.test(s)) return ['Le récit organise des événements selon un ordre, un rythme et un point de vue. Le narrateur peut être personnage ou extérieur à l’histoire. La focalisation détermine la quantité d’informations donnée au lecteur. Les temps verbaux contribuent à distinguer premier plan, arrière-plan et description.','Un récit à focalisation interne limite l’information à ce qu’un personnage perçoit ou sait, tandis qu’une focalisation omnisciente peut donner accès à plusieurs consciences et à des informations inconnues des personnages.','Identifier narrateur, point de vue, temps, organisation des événements et effets produits avant d’interpréter le passage.'];
  if(/poésie/.test(s)) return ['La poésie travaille le langage par le rythme, les sonorités, les images et la disposition du texte. La métaphore, la comparaison, la personnification, les répétitions et les jeux de sons produisent des effets qui participent au sens.','Une répétition peut insister sur une émotion ; une métaphore peut transformer la manière de percevoir un paysage ou une personne. L’analyse doit toujours relier le procédé à son effet.','Citer un élément précis, nommer le procédé, expliquer son fonctionnement puis montrer ce qu’il apporte au sens ou à l’émotion.'];
  if(/théâtre/.test(s)) return ['Le théâtre est un texte destiné à la représentation. Les répliques, didascalies, gestes, déplacements, silences et rapports de pouvoir construisent la scène. Le conflit dramatique peut être explicite ou se révéler progressivement par le dialogue.','Deux personnages peuvent employer des phrases très courtes, des interruptions et des questions pour créer une tension. L’analyse doit tenir compte de ce que les mots font aux relations entre personnages.','Identifier qui parle, à qui, dans quel but, puis observer rythme, lexique, didascalies et rapports de force.'];
  return [DOMAINE.franc.base,'Analyse un court passage en distinguant ce qui est dit, comment c’est dit et l’effet produit sur le lecteur.','Citation courte → procédé ou notion → explication → interprétation.'];
 }
 if(id==='angl'){
  if(/identity|personal/.test(s)) return ['Identity is expressed through personal information, relationships, interests, values and experiences. At upper-secondary level, learners should move beyond isolated sentences and build connected speech using appropriate tense, linking words and precise vocabulary.','I have lived in Abidjan for three years and I enjoy science because I would like to work in engineering. The present perfect links a past situation to the present, while would like expresses a future-oriented wish.','Plan the message, choose the tense from the time reference, connect ideas with because/however/therefore, then check subject-verb agreement.'];
  if(/education|school|career|employment/.test(s)) return ['Talking about education and careers requires vocabulary for subjects, skills, qualifications, responsibilities and future plans. English distinguishes routines from current situations and future intentions through tense and modal structures.','I usually revise in the evening, but this week I am preparing a project. After school, I am going to apply for an internship because I want to gain experience.','Identify time markers, select the tense, organise ideas and support opinions with reasons or examples.'];
  if(/environment|climate|sustainable/.test(s)) return ['Environmental topics require language for causes, consequences, solutions and conditions. Useful structures include should, must, because, therefore and the first conditional.','If communities reduce plastic waste, rivers will be less polluted. People should also protect wetlands because they support biodiversity.','State the problem, explain a cause or consequence, propose a realistic solution and connect ideas logically.'];
  if(/technology|science|media|information/.test(s)) return ['Digital and scientific topics require precise vocabulary and careful distinction between information, evidence and opinion. Learners should be able to describe processes, explain benefits and risks and evaluate reliability.','A website can provide useful information, but the author, date and supporting evidence should be checked before the information is reused.','Identify the purpose and audience, select precise vocabulary, distinguish fact from opinion and justify a conclusion.'];
  return [DOMAINE.angl.base,'Build a short spoken or written production around the chapter theme, then revise grammar, vocabulary, connectors and register.','Context → key vocabulary → grammar choice → connected production → self-correction.'];
 }
 if(id==='hg'){
  if(/guerre|colonisation|décolonisation|indépend/.test(s)) return ['L’analyse historique repose sur des repères chronologiques, des acteurs et des rapports de causalité. Un événement n’a généralement pas une cause unique : il résulte d’un ensemble de facteurs et produit des conséquences à différentes échelles.','Pour étudier une indépendance, distinguer contexte colonial, revendications, acteurs, négociations ou conflits, date de l’indépendance et conséquences politiques et sociales.','Situer → contextualiser → identifier les acteurs → expliquer causes et déroulement → distinguer conséquences immédiates et durables.'];
  if(/population|urbanisation|territoire|migration/.test(s)) return ['La géographie étudie les sociétés dans l’espace. Une population se caractérise par des effectifs, une répartition, des mobilités et des dynamiques. L’urbanisation transforme les espaces et produit des besoins en logements, transports, services et emplois.','Une croissance urbaine rapide peut concentrer les activités mais aussi créer des problèmes de mobilité, d’assainissement et d’accès aux services.','Lire la carte ou les données, localiser, mesurer la dynamique, expliquer les facteurs puis discuter les conséquences.'];
  if(/économie|développement|mondialisation|échanges/.test(s)) return ['Les espaces économiques sont reliés par des flux de marchandises, capitaux, personnes et informations. La mondialisation renforce les interdépendances mais les bénéfices et les contraintes sont inégalement répartis selon les territoires.','Un port relie un territoire national aux échanges internationaux. Son activité dépend des infrastructures, des routes commerciales, des entreprises et de la demande.','Identifier les flux, les acteurs, les territoires reliés et les facteurs d’attractivité avant de conclure sur les effets.'];
  if(/environnement|ressources|changements/.test(s)) return ['Les ressources naturelles sont exploitées pour répondre aux besoins des sociétés. Leur gestion pose des questions de disponibilité, de renouvellement, de pollution et d’équité entre territoires et générations.','Une ressource renouvelable peut devenir vulnérable si son prélèvement dépasse sa capacité de renouvellement.','Identifier ressource, usages, acteurs, pressions et solutions ; distinguer protection, gestion et développement.'];
  return [DOMAINE.hg.base,'Étudie un document, relève les informations vérifiables, puis construis une explication qui distingue description et interprétation.','Repères → documents → acteurs/espaces → causes/conséquences → conclusion.'];
 }
 if(id==='philo'){
  if(/liberté|déterminisme|responsabilité/.test(s)) return ['La liberté peut désigner absence de contrainte, capacité de choisir ou autonomie. Le déterminisme affirme que les événements ont des causes ; il ne suffit pas d’en déduire immédiatement que toute liberté est impossible. La responsabilité pose la question des conditions dans lesquelles une action peut être attribuée à un sujet.','Une personne influencée par son histoire et son environnement n’est pas nécessairement sous une contrainte physique. La question devient alors : reconnaître les déterminations empêche-t-il toute autonomie ?','Définir les concepts, formuler le problème, présenter une première thèse, construire une objection puis examiner les conditions d’une réponse plus nuancée.'];
  if(/vérité|connaissance/.test(s)) return ['La vérité concerne ce qui est effectivement le cas, tandis que la connaissance suppose un rapport justifié à ce qui est tenu pour vrai. Opinion, croyance et savoir ne se distinguent pas seulement par le degré de certitude mais par le type de justification.','Une rumeur peut être vraie par hasard sans constituer un savoir. Une connaissance exige des raisons, des méthodes de vérification et la prise en compte des limites.','Définir vérité, opinion et connaissance, examiner un exemple, faire apparaître une difficulté puis comparer les critères de justification.'];
  if(/justice|droit|état|politique/.test(s)) return ['Le droit organise la vie collective par des règles reconnues, tandis que la justice interroge ce qui doit être considéré comme juste. Égalité de traitement et équité ne sont pas toujours identiques : une même règle peut avoir des effets différents selon les situations.','Une règle identique pour tous réalise une égalité formelle ; une politique peut chercher à compenser une inégalité de situation. La philosophie demande alors quel critère permet de justifier la différence de traitement.','Distinguer légalité, justice, égalité et équité, puis confronter plusieurs critères avant de prendre position argumentativement.'];
  if(/travail|technique/.test(s)) return ['Le travail transforme la nature et les capacités humaines. La technique augmente les possibilités d’action mais peut aussi créer de nouvelles dépendances, modifier l’organisation du travail et poser des problèmes sociaux ou environnementaux.','Une machine peut réduire un effort physique tout en augmentant la cadence et en transformant les compétences demandées.','Analyser les bénéfices et les coûts d’une transformation technique sans confondre progrès matériel et amélioration automatique de toute situation humaine.'];
  return [DOMAINE.philo.base,'Construis une distinction conceptuelle, une thèse, une objection et une réponse argumentée à partir d’un exemple concret.','Définitions → problème → thèse → objection → discussion → réponse argumentée.'];
 }
 if(id==='info'){
  if(/algorithm|programm|structures/.test(s)) return ['Un algorithme décrit une suite finie et ordonnée d’instructions permettant de résoudre une classe de problèmes. Une solution robuste distingue données d’entrée, traitement et résultat. Les conditions et répétitions permettent de contrôler le déroulement ; les tests vérifient le comportement sur plusieurs cas.','Pour déterminer le maximum de trois nombres, on peut initialiser une variable au premier nombre puis comparer successivement les autres valeurs et mettre à jour le maximum.','Décomposer le problème, écrire les étapes en langage clair, identifier les variables, tester cas normal et cas limites, puis corriger.'];
  if(/base de données|données/.test(s)) return ['Une base de données organise des informations pour permettre leur recherche et leur mise à jour. Une table regroupe des enregistrements et des champs ; une clé identifie de manière fiable un enregistrement. Une requête sélectionne ou transforme les données selon des critères.','Dans une table Élèves, un identifiant unique permet de distinguer deux élèves portant le même nom. Une requête peut ensuite sélectionner les élèves d’une classe donnée.','Identifier entités et attributs, choisir une clé, éviter les doublons inutiles et tester les requêtes sur plusieurs cas.'];
  if(/réseau|internet|protocol/.test(s)) return ['Un réseau permet à des équipements d’échanger des données. Les protocoles définissent des règles communes. Sur Internet, les données circulent entre réseaux ; les services comme le Web utilisent des protocoles spécifiques. La sécurité exige authentification, chiffrement et vigilance face aux messages ou sites malveillants.','Une page Web est demandée par un client à un serveur ; le nom de domaine permet d’identifier le service demandé avant l’établissement de la communication.','Identifier émetteur, destinataire, données, protocole et risque ; protéger les comptes et vérifier les sources avant d’agir.'];
  if(/sécurité|éthique/.test(s)) return ['La sécurité informatique protège confidentialité, intégrité et disponibilité des données. Les mots de passe robustes, l’authentification à plusieurs facteurs, les mises à jour et les sauvegardes réduisent les risques. L’éthique demande aussi de respecter la vie privée et les droits des personnes.','Une sauvegarde permet de récupérer des données après une suppression ou une attaque, mais elle ne remplace pas la prévention : il faut aussi protéger les comptes et limiter les accès.','Identifier la menace, évaluer la conséquence, appliquer une mesure de prévention puis prévoir une récupération.'];
  return [DOMAINE.info.base,'Modélise un problème concret, propose une solution, teste-la sur plusieurs entrées et explique les corrections effectuées.','Problème → décomposition → solution → test → correction → validation.'];
 }
 if(id==='eps'){
  if(/endurance|effort|condition/.test(s)) return ['L’endurance correspond à la capacité à maintenir un effort dans la durée. La gestion de l’effort dépend de l’intensité, de la durée, des pauses, de la respiration et de l’état de forme. Un entraînement progressif cherche à provoquer une adaptation sans dépasser les capacités de récupération.','Sur une course longue, partir trop vite peut provoquer une baisse importante de l’allure. Une allure régulière et adaptée permet de mieux répartir l’effort.','S’échauffer, choisir une intensité adaptée, mesurer sa performance, observer ses sensations et récupérer progressivement.'];
  if(/athlétisme|performance/.test(s)) return ['Une performance athlétique dépend de facteurs techniques, physiques et psychologiques. La vitesse, la fréquence gestuelle, la coordination, la force et la qualité du départ peuvent modifier le résultat. L’amélioration passe par une observation précise et des objectifs progressifs.','En sprint, une meilleure posture et une accélération progressive peuvent améliorer la transmission des forces vers le sol.','Observer un critère précis, modifier un seul élément technique, répéter puis comparer les résultats.'];
  if(/sports collectifs|stratég/.test(s)) return ['Dans un sport collectif, la performance dépend de la coopération, de l’occupation de l’espace, de la circulation du ballon ou de l’objet et de la prise d’information. Une stratégie n’est efficace que si elle est adaptée à la situation réelle.','Créer de la largeur peut ouvrir un espace central ; un déplacement sans ballon peut donc être aussi important que l’action du porteur.','Observer partenaires, adversaires et espace disponible avant de choisir une action ; communiquer et se replacer après l’action.'];
  if(/santé|récupération|blessure/.test(s)) return ['La santé en EPS dépend de la progressivité de l’effort, de l’échauffement, de l’hydratation, du sommeil et de la récupération. Une douleur inhabituelle ou importante ne doit pas être ignorée. La prévention consiste à réduire les facteurs de risque plutôt qu’à attendre l’accident.','Après une séance intense, un retour au calme progressif et une hydratation adaptée participent à la récupération.','Préparer le corps, respecter les consignes, écouter les signaux corporels, récupérer et signaler une situation anormale.'];
  return [DOMAINE.eps.base,'Décris une séance, identifie l’objectif, les critères de réussite et les règles de sécurité, puis propose un moyen de mesurer les progrès.','Objectif → échauffement → réalisation → observation → ajustement → récupération.'];
 }
 if(id==='arts'){
  return [DOMAINE.arts.base,'Analyse une production en distinguant intention, choix plastiques visibles, matériau/support, organisation de l’espace et effet produit sur le spectateur.','Observer → décrire → interpréter → justifier les choix → proposer une amélioration.'];
 }
 if(id==='ecm'){
  if(/droit|liberté/.test(s)) return ['Les droits et libertés protègent la dignité et la participation des personnes, mais leur exercice s’inscrit dans un cadre juridique qui protège également autrui. Comprendre un droit suppose de connaître son principe, ses limites légales et les institutions chargées de le protéger.','La liberté d’expression permet de communiquer des idées, mais elle ne signifie pas que toute atteinte aux droits d’autrui est autorisée.','Identifier le droit concerné, le principe, la règle applicable, les responsabilités et les recours possibles.'];
  if(/paix|conflit/.test(s)) return ['La prévention des conflits repose sur le dialogue, l’écoute, la médiation et la recherche d’accords. La paix ne se réduit pas à l’absence de violence : elle suppose aussi des mécanismes permettant de traiter les désaccords et de préserver les droits.','Dans un conflit scolaire, écouter séparément les parties, identifier les faits et rechercher une solution acceptable peut éviter l’escalade.','Distinguer faits, émotions, intérêts et règles ; rechercher une solution proportionnée et respectueuse des droits.'];
  if(/environnement|développement/.test(s)) return ['Le développement durable cherche à répondre aux besoins présents sans compromettre les capacités futures. Il met en relation dimensions environnementale, économique et sociale. Une décision responsable examine ses effets et les acteurs concernés.','Une politique de gestion des déchets peut réduire la pollution, créer des emplois et demander un financement : les trois dimensions doivent être considérées ensemble.','Identifier problème, acteurs, effets, contraintes et solutions ; comparer les conséquences à court et long terme.'];
  return [DOMAINE.ecm.base,'Étudie une situation concrète, distingue faits, règles, droits, devoirs et responsabilités, puis propose une action proportionnée.','Situation → principe → règle → responsabilités → conséquences → action.'];
 }
 return [DOMAINE[id]?.base||'Étudie la notion, relie-la à un exemple et justifie tes réponses.','Construis un exemple concret et explique chaque étape.','Comprendre → appliquer → justifier → vérifier.'];
}

function course(id,n,t,core){
 const [notion,exemple,methode]=core;
 return '# '+t+'\\n\\n## Niveau '+n+'\\n\\n## 1. Problématique\\nPourquoi cette notion est-elle importante et dans quelles situations doit-on la mobiliser ? Le chapitre doit permettre de passer de la connaissance à l’analyse et à l’application.\\n\\n## 2. Cours développé\\n'+notion+'\\n\\n## 3. Exemple guidé\\n'+exemple+'\\n\\n## 4. Mise en relation\\n'+DOMAINE[id].base+'\\n\\n## 5. Méthode\\n'+methode+'\\n\\n## 6. Activité d’apprentissage\\nÀ partir d’une situation nouvelle liée à « '+t+' », relève les données ou indices utiles, formule ce qui doit être expliqué ou réalisé, puis construis une réponse complète. Compare ensuite ta réponse aux critères de réussite du chapitre et améliore-la.\\n\\n## 7. Points de vigilance\\n- ne pas confondre une définition et une explication ;\\n- ne pas donner une conclusion sans montrer le raisonnement ;\\n- utiliser les unités, termes techniques ou indices nécessaires ;\\n- vérifier que la réponse correspond exactement à la question ;\\n- distinguer ce qui est observé de ce qui est interprété.\\n\\n## 8. Bilan\\nÀ la fin du chapitre, l’élève doit pouvoir définir les notions, expliquer le mécanisme ou le raisonnement, traiter un exercice guidé puis transférer la méthode à une situation différente.';
}
function exercices(id,n,t,core){
 const [notion,exemple,methode]=core;
 return '# Exercices et corrections — '+t+'\\n\\n## Exercice 1 — Compréhension\\nExplique la notion centrale du chapitre et montre son utilité dans une situation concrète.\\n\\n### Correction\\nUne bonne réponse définit la notion, donne son rôle et la relie à un exemple pertinent.\\n\\n## Exercice 2 — Application guidée\\nTraite cette situation : '+exemple+'\\n\\n### Correction\\n'+methode+' La réponse finale doit être formulée après la justification.\\n\\n## Exercice 3 — Analyse\\nRelève deux informations importantes dans une situation portant sur « '+t+' » et explique le lien entre elles.\\n\\n### Correction\\nIl faut sélectionner les informations utiles, mobiliser la notion du cours et expliciter le lien au lieu de juxtaposer les éléments.\\n\\n## Exercice 4 — Transfert\\nPropose une situation nouvelle dans laquelle la connaissance « '+t+' » permet de résoudre un problème ou d’expliquer un phénomène.\\n\\n### Correction\\nLa situation doit être différente de l’exemple initial mais la méthode doit rester identifiable.\\n\\n## Méthode à retenir\\n'+methode;
}
function renforcement(id,n,t,core){
 const [notion,exemple,methode]=core;
 return '# Renforcement — '+t+'\\n\\n## Situation-problème\\nUn élève connaît la définition de « '+t+' » mais échoue lorsqu’il doit l’utiliser dans une situation nouvelle. On lui demande de reprendre le problème en explicitant son raisonnement.\\n\\n## Travail\\n1. Reformule la notion.\\n2. Repère les indices ou données.\\n3. Choisis la méthode.\\n4. Réalise les étapes.\\n5. Justifie le résultat.\\n6. Vérifie et corrige.\\n\\n## Correction détaillée attendue\\nLa résolution doit relier la situation à la notion du cours et faire apparaître les étapes. Une simple réponse finale ne suffit pas lorsque le raisonnement est demandé. Exemple de démarche : '+methode+'\\n\\n## Consolidation\\nCompare cette situation à l’exemple guidé du cours : indique ce qui est identique dans la méthode et ce qui change dans les données ou le contexte.\\n\\n## Défi\\nExplique le chapitre en trois minutes à un camarade puis invente une question qu’il doit résoudre sans consulter le cours.';
}
function quiz(t,core){
 const [notion]=core;
 const base=[
  ['La compréhension d’une notion suppose-t-elle de pouvoir la réutiliser dans une situation nouvelle ?',['Oui','Non'],0,'Oui : le transfert montre que la connaissance n’est pas seulement mémorisée.'],
  ['Une justification doit-elle relier la réponse aux données ou aux notions utilisées ?',['Oui','Non'],0,'Oui : elle rend le raisonnement compréhensible et vérifiable.'],
  ['Faut-il vérifier les unités ou le vocabulaire technique lorsqu’ils sont nécessaires ?',['Oui','Non'],0,'Oui : ils participent à la précision de la réponse.'],
  ['Une conclusion doit-elle répondre directement à la question posée ?',['Oui','Non'],0,'Oui : elle doit être cohérente avec le raisonnement.'],
  ['Peut-on confondre une observation avec une interprétation ?',['Oui','Non'],1,'Non : une observation est un élément constaté, une interprétation lui donne un sens.'],
  ['Le chapitre doit-il être relié à des exemples et à des situations d’application ?',['Oui','Non'],0,'Oui : les exemples permettent de comprendre comment la notion fonctionne.']
 ];
 return base.map((q,i)=>({id:'q'+(i+1),type:'qcm',enonce:q[0]+' — '+t,choix:q[1],bonnesReponses:[q[2]],reponseAttendue:'',explication:q[3],points:1}));
}
function fiche(t,core){
 const [notion,exemple,methode]=core;
 return '# Fiche de révision — '+t+'\\n\\n## Notion centrale\\n'+notion+'\\n\\n## Exemple repère\\n'+exemple+'\\n\\n## Méthode express\\n'+methode+'\\n\\n## Je dois savoir\\n☐ définir les notions ;\\n☐ expliquer le mécanisme ou raisonnement ;\\n☐ traiter un exercice ;\\n☐ justifier ma réponse ;\\n☐ transférer la méthode à une situation nouvelle.\\n\\n## Auto-évaluation\\nSi je peux expliquer le chapitre sans regarder le cours et résoudre une situation différente de l’exemple, le chapitre est compris.';
}

(async()=>{
 let chapitres=0,updated=0,created=0;
 const snap=await db.collection('ca_chapitres').where('anneeScolaire','==','2026-2027').where('niveau','in',NIVEAUX).limit(1000).get();
 for(const d of snap.docs){
   const c={id:d.id,...d.data()}; const id=String(c.matiereId); if(!MATIERES.includes(id)) continue;
   const core=specific(id,String(c.titre||''));
   const types=[
    ['cours','Cours approfondi — '+c.titre,course(id,c.niveau,c.titre,core),[],45],
    ['exercice','Exercices et corrections — '+c.titre,exercices(id,c.niveau,c.titre,core),[],30],
    ['renforcement','Renforcement — '+c.titre,renforcement(id,c.niveau,c.titre,core),[],25],
    ['quiz','QCM — '+c.titre,'QCM de consolidation des acquis.',quiz(c.titre,core),10],
    ['fiche','Fiche de révision — '+c.titre,fiche(c.titre,core),[],15]
   ];
   for(let i=0;i<types.length;i++){
    const [type,titre,contenu,questions,duree]=types[i];
    const old=await db.collection('ca_ressources').where('chapitreId','==',c.id).where('type','==',type).limit(1).get();
    let rich=false;
    if(!old.empty){
      const x=old.docs[0].data(), len=String(x.contenu||'').trim().length, nq=Array.isArray(x.questions)?x.questions.length:0;
      rich=type==='quiz'?nq>=6:len>=1800;
    }
    if(rich) continue;
    const ref=old.empty?db.collection('ca_ressources').doc(c.id+'_lycee_v2_'+type):old.docs[0].ref;
    await ref.set({type,titre,ordre:i+1,chapitreId:c.id,niveau:c.niveau,matiereId:id,ecoleId:'',contenu,imagesUrls:[],pdfUrl:'',videoYoutubeId:'',enonce:'',solution:'',difficulte:type==='quiz'?2:1,ressourceLieeId:'',questions,dureeMinutes:duree,examen:'',annee:2026,serie:'',actif:true,ressourceNationale:true,auteur:'Sentinel CI — cours approfondi',dateCreation:old.empty?FieldValue.serverTimestamp():(old.docs[0].data().dateCreation||FieldValue.serverTimestamp()),dateMaj:FieldValue.serverTimestamp()},{merge:true});
    old.empty?created++:updated++;
   }
   chapitres++;
 }
 await db.collection('ca_parametres').doc('version').set({version:FieldValue.increment(1),dateMaj:FieldValue.serverTimestamp()},{merge:true});
 console.log(JSON.stringify({ok:true,chapitres,updated,created},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
