const { initializeApp, applicationDefault } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');

initializeApp({ credential: applicationDefault(), projectId: 'sentinel-ci-c7592' });
const db = getFirestore();

const lessons = {
  'francais-6e': [
    ['Dialogue oral','Un dialogue oral met en relation au moins deux interlocuteurs. Chacun doit écouter, attendre son tour et adapter son langage à la situation. On distingue la prise de parole, la question, la réponse, la reformulation et la conclusion.','Situation : demander un renseignement au marché. « Bonjour madame, pourriez-vous me dire où se trouve le rayon du riz ? » La réponse doit rester claire et polie.','Repère les interlocuteurs, le but de l’échange et les formules de politesse. Puis transforme une phrase trop familière en phrase adaptée.',['Quel comportement facilite un dialogue ?','Écouter et attendre son tour.','Que faut-il adapter ?','Le vocabulaire et le niveau de langue.']],
    ['Expression écrite','Écrire consiste à transformer des idées en un texte organisé. Avant de rédiger, il faut comprendre la consigne, chercher les idées, les classer, rédiger puis relire. Une production réussie respecte le sujet, utilise des connecteurs et comporte des phrases correctement construites.','Pour raconter une sortie scolaire, on peut organiser le texte ainsi : lieu et départ, activités réalisées, événement marquant, retour et bilan.','Rédige huit à dix lignes sur une journée mémorable. Souligne ensuite trois connecteurs et vérifie les accords sujet-verbe.',['Quelle est la première étape ?','Comprendre la consigne.','Pourquoi relire ?','Pour corriger le sens, les accords et la ponctuation.']],
    ['Récit','Un récit présente des événements dans un ordre compréhensible. La situation initiale présente le cadre, l’élément déclencheur lance l’action, les péripéties développent l’histoire et la situation finale la termine. Les temps verbaux et les connecteurs organisent la chronologie.','« Un matin, Awa partit tôt. Soudain, elle entendit un bruit. Elle s’approcha, puis découvrit un petit chien perdu. »','Remets cinq événements dans l’ordre et rédige une suite en utilisant d’abord, ensuite, soudain, enfin.',['Quel élément déclenche l’action ?','L’événement déclencheur.','À quoi servent les connecteurs ?','À organiser les étapes du récit.']],
    ['Description','Décrire revient à donner des informations précises sur une personne, un lieu, un objet ou une scène. On part du général vers le particulier et on utilise des adjectifs, des groupes nominaux enrichis et des repères spatiaux.','« La cour est vaste. Au fond, sous un grand arbre, deux bancs entourent un petit jardin fleuri. »','Décris ta salle de classe en indiquant sa forme, ses objets et la position d’au moins quatre éléments.',['Que doit permettre une bonne description ?','Se représenter précisément ce qui est décrit.','Quels mots indiquent la position ?','Par exemple devant, derrière, à côté, sous.']],
    ['Poésie','La poésie travaille les mots, les sons, les images et le rythme. Un vers est une ligne du poème et une strophe regroupe plusieurs vers. Une comparaison rapproche deux éléments avec un outil comme « comme » ; une métaphore établit le rapprochement sans cet outil.','« La lune brille comme une lampe » contient une comparaison. « La lune est une lampe dans la nuit » utilise une métaphore.','Repère les vers et les strophes d’un court poème puis invente une comparaison et une métaphore sur la pluie.',['Qu’est-ce qu’un vers ?','Une ligne du poème.','Quel mot peut introduire une comparaison ?','Comme.']],
    ['Théâtre','Au théâtre, les personnages parlent et agissent devant un public. Les répliques indiquent les paroles prononcées et les didascalies donnent des indications de gestes, de ton ou de déplacement. Le lecteur doit identifier le personnage qui parle et son intention.','PERSONNAGE A : Où vas-tu ?\nPERSONNAGE B : À la bibliothèque.\n(Didascalie : il prend son sac et sort.)','Transforme une courte scène narrative en dialogue théâtral avec deux personnages et deux didascalies.',['Que sont les didascalies ?','Des indications de mise en scène.','Que doit-on identifier dans une scène ?','Les personnages, leurs paroles et leurs actions.']],
    ['Nom et déterminant','Le nom désigne une personne, un animal, un objet, un lieu ou une idée. Le déterminant accompagne généralement le nom et indique notamment son genre et son nombre. Les articles définis sont le, la, les ; les articles indéfinis sont un, une, des.','Dans « les grandes maisons », « maisons » est un nom féminin pluriel, « les » est le déterminant et « grandes » est un adjectif.','Dans dix groupes nominaux, souligne le déterminant, entoure le nom et indique le genre et le nombre.',['Quel mot accompagne le nom ?','Le déterminant.','Dans « une table », quel est le genre ?','Féminin.']],
    ['Adjectif qualificatif','L’adjectif qualificatif précise une caractéristique du nom. Il s’accorde généralement avec lui en genre et en nombre. Pour trouver l’adjectif, on peut demander quelle caractéristique est donnée au nom.','Un petit garçon, une petite fille, des petits garçons, des petites filles. L’adjectif « petit » change selon le genre et le nombre.','Accorde les adjectifs dans huit phrases puis enrichis quatre groupes nominaux avec un adjectif précis.',['Avec quoi l’adjectif s’accorde-t-il ?','Avec le nom.','Que faut-il vérifier ?','Le genre et le nombre.']],
    ['Verbe et sujet','Le sujet indique qui fait l’action ou de qui l’on parle. Le verbe indique une action ou un état et s’accorde avec le sujet. Pour trouver le sujet, on peut poser « qui est-ce qui ? » devant le verbe.','Dans « Les élèves révisent leurs leçons », « les élèves » est le sujet et « révisent » est le verbe.','Souligne les verbes de dix phrases, encadre les sujets et explique deux accords sujet-verbe.',['Qui commande l’accord du verbe ?','Le sujet.','Comment trouver le sujet ?','En posant « qui est-ce qui ? ».']],
    ['Temps du récit','Les temps verbaux organisent le récit. L’imparfait sert souvent à décrire, présenter une habitude ou installer un cadre. Le passé composé exprime fréquemment une action achevée. Le présent peut rendre une scène plus vivante.','« Il faisait nuit quand Awa a entendu un bruit. » L’imparfait installe le cadre ; le passé composé marque l’événement.','Transforme un court récit au présent vers un récit au passé en conservant la chronologie.',['À quoi sert souvent l’imparfait ?','À décrire ou exprimer une habitude.','Que marque souvent le passé composé ?','Une action achevée.']],
    ['Phrase complexe','Une phrase complexe contient plusieurs verbes conjugués et donc généralement plusieurs propositions. Les propositions peuvent être coordonnées ou reliées par des mots comme parce que, lorsque, si. Pour l’analyser, on repère d’abord les verbes conjugués.','« Je reste à la maison parce qu’il pleut. » contient deux verbes conjugués : reste et pleut.','Découpe cinq phrases complexes en propositions puis indique le mot qui les relie.',['Combien de verbes conjugués peut contenir une phrase complexe ?','Plus d’un.','Quelle est la première étape de l’analyse ?','Repérer les verbes conjugués.']],
    ['Vocabulaire','Le vocabulaire permet de choisir le mot juste. Un synonyme a un sens proche, un antonyme un sens contraire et un mot de la même famille partage une base commune. Le contexte aide à comprendre un mot inconnu.','« Commencer » et « débuter » sont synonymes. « Grand » et « petit » sont antonymes. « Chanter » et « chanteur » appartiennent à la même famille.','Trouve un synonyme, un antonyme et un mot de la même famille pour chacun de cinq mots.',['Qu’est-ce qu’un synonyme ?','Un mot de sens proche.','À quoi sert le contexte ?','À aider à comprendre le sens d’un mot.']]
  ],
  'physique_chimie-6e': [
    ['Circuit électrique','Un circuit simple forme une boucle comprenant un générateur, un récepteur et des conducteurs. Le courant ne peut circuler dans le circuit complet que si la boucle est fermée. Un schéma électrique utilise des symboles conventionnels.','Une pile reliée à une lampe par deux fils forme un circuit fermé : la lampe peut s’allumer. Si un fil est débranché, la boucle est ouverte.','Dessine le schéma d’une pile, d’un interrupteur et d’une lampe. Explique ce qui change lorsque l’interrupteur est ouvert.',['Condition du fonctionnement ?','Le circuit doit être fermé.','Que fournit la pile ?','De l’énergie électrique.']],
    ['Commande d’un circuit','Un interrupteur commande le fonctionnement d’un circuit en ouvrant ou fermant la boucle. Il permet donc de contrôler le passage du courant sans débrancher les fils.','Interrupteur fermé : lampe allumée dans un circuit correctement monté. Interrupteur ouvert : lampe éteinte.','Propose un montage permettant de commander une lampe à distance avec un interrupteur et explique les deux états.',['Rôle de l’interrupteur ?','Ouvrir ou fermer le circuit.','Quand la boucle est-elle interrompue ?','Quand l’interrupteur est ouvert.']],
    ['Court-circuit et protection','Un court-circuit relie directement des points du circuit par un chemin de très faible résistance. Le courant peut alors devenir très important et provoquer un échauffement. Les fusibles et disjoncteurs interrompent le circuit en cas de courant dangereux.','Relier directement les deux bornes d’une pile avec un conducteur est dangereux : le conducteur et la pile peuvent chauffer.','Explique pourquoi on ne doit jamais relier directement les bornes d’une pile et cite un dispositif de protection domestique.',['Risque principal ?','Un échauffement important.','Dispositif de protection ?','Un fusible ou un disjoncteur.']],
    ['Propriétés des liquides','Un liquide possède un volume propre mais pas de forme propre : il prend la forme du récipient. Au repos, sa surface libre est horizontale. Les liquides sont peu compressibles.','Verser 200 mL d’eau dans un verre change la forme occupée par l’eau mais pas la quantité d’eau.','Mesure 50 mL d’eau avec une éprouvette graduée et décris la position de la surface libre.',['Un liquide a-t-il une forme propre ?','Non.','Que devient sa surface au repos ?','Elle est horizontale.']],
    ['Les gaz','Un gaz n’a ni forme ni volume propres. Il occupe l’espace disponible et peut être comprimé. L’air est un mélange de gaz. Un gaz exerce une pression sur les parois du récipient.','Une seringue bouchée contient de l’air : pousser le piston comprime l’air et augmente la pression ressentie.','Explique pourquoi une seringue contenant de l’air peut être comprimée alors qu’une seringue remplie d’eau l’est beaucoup moins.',['Un gaz peut-il être comprimé ?','Oui.','Que contient l’air ?','Un mélange de gaz.']],
    ['Température','La température caractérise l’état thermique d’un corps. Elle se mesure avec un thermomètre, souvent en degrés Celsius. Il faut attendre la stabilisation de la mesure et éviter de tenir directement le réservoir du thermomètre.','Une eau à 20 °C est moins chaude qu’une eau à 40 °C. La température ne mesure pas directement la quantité de matière.','Mesure la température d’un liquide sans toucher le fond du récipient et note la valeur après stabilisation.',['Avec quel instrument mesure-t-on la température ?','Un thermomètre.','Unité courante ?','Le degré Celsius.']],
    ['Changements d’état de l’eau','L’eau peut être solide, liquide ou gazeuse. La fusion transforme un solide en liquide, la solidification l’inverse, la vaporisation transforme le liquide en gaz et la liquéfaction transforme le gaz en liquide.','La glace fond : solide vers liquide. La vapeur qui se condense sur une surface froide redevient liquide.','Complète un schéma reliant les trois états de l’eau aux quatre changements d’état.',['Solide vers liquide ?','Fusion.','Gaz vers liquide ?','Liquéfaction.']],
    ['Constituants de l’air','L’air est un mélange de gaz. Il contient majoritairement du diazote et du dioxygène, ainsi que d’autres constituants en plus faible quantité. Le dioxygène participe notamment à la respiration et aux combustions.','Une bougie placée sous un récipient fermé finit par s’éteindre lorsque le dioxygène disponible devient insuffisant.','Explique l’extinction d’une bougie sous un verre en utilisant le mot dioxygène.',['L’air est-il un corps pur ?','Non, c’est un mélange.','Quel gaz entretient une combustion ?','Le dioxygène.']],
    ['Combustion d’un solide et d’un liquide','Une combustion est une transformation chimique entre un combustible et un comburant. Elle libère souvent de l’énergie sous forme de chaleur et parfois de lumière. Le dioxygène de l’air est un comburant fréquent.','Lorsqu’une bougie brûle, la cire vaporisée réagit avec le dioxygène. La flamme produit de la chaleur et de la lumière.','Identifie le combustible et le comburant dans une combustion de bougie et explique pourquoi une flamme peut s’éteindre.',['Deux éléments nécessaires ?','Un combustible et un comburant, avec une énergie d’activation suffisante.','Comburant courant ?','Le dioxygène.']],
    ['Combustion d’un gaz','Un gaz combustible peut brûler en présence de dioxygène. Une combustion complète produit notamment du dioxyde de carbone et de l’eau. Une arrivée d’air insuffisante peut favoriser une combustion incomplète.','Le butane d’un briquet brûle avec le dioxygène de l’air. Une flamme jaune et un appareil mal ventilé doivent alerter.','Explique pourquoi une bonne ventilation est importante lors de l’utilisation d’un appareil à gaz.',['Produit d’une combustion complète du butane ?','Notamment dioxyde de carbone et eau.','Danger d’une mauvaise combustion ?','Formation possible de monoxyde de carbone.']],
    ['Dangers des combustions','Les combustions peuvent provoquer brûlures, incendies, explosions et intoxications. Le monoxyde de carbone est particulièrement dangereux car il est invisible et inodore. La prévention repose sur la ventilation et le respect des consignes.','Un appareil à gaz utilisé dans une pièce mal ventilée peut produire une situation dangereuse.','Cite trois règles de sécurité pour une combustion et explique pourquoi chacune est utile.',['Pourquoi ventiler ?','Pour renouveler l’air et limiter l’accumulation de gaz dangereux.','Le monoxyde de carbone est-il visible ?','Non.']],
    ['Volume et masse','Le volume mesure l’espace occupé et s’exprime notamment en litre ou mètre cube. La masse mesure la quantité de matière et s’exprime en gramme ou kilogramme. Une balance mesure la masse ; une éprouvette mesure le volume d’un liquide.','1 L = 1000 mL. Une masse de 500 g correspond à 0,5 kg.','Convertis des volumes et masses puis choisis l’instrument adapté à chaque mesure.',['Instrument pour la masse ?','Une balance.','Combien de millilitres dans un litre ?','1000 mL.']]
  ],
  'svt-6e': [
    ['Reproduction chez les vertébrés','La reproduction permet de produire de nouveaux individus et d’assurer la continuité de l’espèce. Les mâles produisent des spermatozoïdes et les femelles des ovules. La fécondation correspond à leur rencontre et le développement du jeune varie selon les espèces.','Chez certains vertébrés, les œufs se développent à l’extérieur ; chez d’autres, le jeune se développe dans le corps de la mère.','Compare deux vertébrés en indiquant le lieu de développement du jeune et le mode de fécondation.',['Cellules reproductrices mâles ?','Les spermatozoïdes.','Cellules reproductrices femelles ?','Les ovules.']],
    ['Reproduction chez les plantes à fleurs','La fleur porte des organes reproducteurs. Les étamines produisent le pollen ; le pistil comprend notamment le stigmate, le style et l’ovaire. La pollinisation transporte le pollen vers le stigmate. Après fécondation, l’ovule peut devenir une graine et l’ovaire un fruit.','Une abeille transporte du pollen d’une fleur à une autre : elle peut contribuer à la pollinisation.','Légende un schéma de fleur avec étamine, pollen, stigmate, ovaire et ovule puis explique le trajet du pollen.',['Organe qui produit le pollen ?','L’étamine.','Que peut devenir l’ovule après fécondation ?','Une graine.']],
    ['Germination de la graine','Une graine viable germe lorsque les conditions nécessaires sont réunies. Elle a notamment besoin d’eau, d’une température favorable et de dioxygène. La radicule apparaît généralement en premier. Les réserves de la graine nourrissent l’embryon au début.','Une graine placée dans un milieu humide et aéré peut germer, alors qu’une graine totalement sèche ne démarre pas son développement.','Conçois une expérience avec deux lots de graines pour tester le rôle de l’eau et indique la variable observée.',['Besoin indispensable étudié ?','Notamment l’eau, avec une température et une aération adaptées.','Première partie de la jeune racine ?','La radicule.']],
    ['Nutrition chez les vertébrés','Les vertébrés se nourrissent pour obtenir énergie et matière. Les aliments apportent glucides, lipides, protéines, vitamines, sels minéraux et eau. Le régime alimentaire dépend de l’espèce et peut être herbivore, carnivore ou omnivore.','Une vache est principalement herbivore ; un lion est carnivore ; l’être humain est omnivore.','Classe plusieurs animaux selon leur régime alimentaire et justifie chaque classement à partir de leur alimentation.',['Pourquoi un animal se nourrit-il ?','Pour obtenir matière et énergie nécessaires à son organisme.','Trois grands régimes ?','Herbivore, carnivore, omnivore.']],
    ['Nutrition chez les plantes à fleurs','Les plantes vertes fabriquent leur matière organique grâce à la photosynthèse. Elles utilisent notamment de l’eau et du dioxyde de carbone en présence de lumière et libèrent du dioxygène. Les racines absorbent eau et sels minéraux.','Une plante placée à la lumière peut produire de la matière organique dans ses feuilles. Les racines prélèvent l’eau et les sels minéraux du sol.','Explique pourquoi une plante verte a besoin de lumière et identifie les matières premières de la photosynthèse.',['Organe principal de la photosynthèse ?','La feuille.','Deux matières utilisées ?','Eau et dioxyde de carbone.']],
    ['Besoins nutritifs des plantes','La croissance d’une plante dépend de plusieurs facteurs : eau, sels minéraux, dioxyde de carbone, lumière et température adaptée. Une carence peut ralentir la croissance ou modifier l’aspect de la plante.','Une plante privée d’eau se flétrit ; une plante privée de lumière produit moins de matière organique.','Propose un test comparant deux plantes dont un seul facteur varie et explique pourquoi cette précaution est nécessaire.',['Pourquoi ne faire varier qu’un facteur ?','Pour relier l’effet observé au facteur étudié.','Que peut provoquer un manque d’eau ?','Le flétrissement et un ralentissement du développement.']],
    ['Actions néfastes de l’Homme sur l’environnement','Les activités humaines peuvent transformer les milieux par la déforestation, l’urbanisation, l’extraction des ressources et les rejets polluants. Lorsque les modifications sont importantes, les habitats et les équilibres écologiques sont perturbés.','La destruction d’une forêt réduit les habitats disponibles pour de nombreuses espèces.','Étudie un exemple local de transformation d’un milieu et distingue la cause, la conséquence et une action de prévention.',['Exemple d’action humaine ?','La déforestation.','Conséquence possible ?','La perte d’habitats et de biodiversité.']],
    ['Pollution et conséquences','La pollution est une dégradation d’un milieu liée à l’introduction de substances ou d’agents nuisibles. Elle peut toucher l’air, l’eau et le sol et avoir des effets sur les organismes et la santé.','Des déchets plastiques dans une rivière peuvent être ingérés par des animaux ou bloquer certains écoulements.','Classe plusieurs exemples de pollution selon le milieu touché et propose une conséquence pour chacun.',['Trois milieux concernés ?','Air, eau et sol.','Une conséquence sur les êtres vivants ?','Maladie, intoxication, mortalité ou perturbation du milieu.']],
    ['Protection de l’environnement','La protection de l’environnement consiste à réduire les dégradations, économiser les ressources et restaurer les milieux. Réduire les déchets, traiter les eaux usées, protéger les forêts et limiter les pollutions sont des actions complémentaires.','Trier les déchets est utile, mais réduire leur production et réutiliser certains objets agit encore plus en amont.','Construis un plan d’action pour réduire les déchets de ton établissement en trois étapes mesurables.',['Action en amont ?','Réduire la production de déchets.','Pourquoi traiter les eaux usées ?','Pour limiter la pollution des milieux aquatiques.']],
    ['Dégradation des milieux naturels','Un milieu naturel associe des êtres vivants et des éléments physiques. La pollution, l’érosion, la destruction d’habitats ou l’introduction d’espèces invasives peuvent modifier les relations entre organismes et ressources.','Si une zone humide disparaît, les espèces qui utilisent cet habitat perdent des lieux de reproduction ou d’alimentation.','Décris une chaîne de conséquences à partir de la destruction d’un habitat.',['Qu’est-ce qu’un habitat ?','Un lieu offrant les conditions nécessaires à la vie d’un organisme.','Que peut entraîner sa destruction ?','Une diminution ou un déplacement de populations.']],
    ['Solutions aux problèmes environnementaux','Une démarche environnementale commence par identifier une cause, mesurer ses effets, réduire la source et suivre les résultats. Les solutions peuvent être individuelles, collectives et institutionnelles.','Pour une rivière polluée : identifier les sources, stopper les rejets, nettoyer si nécessaire, puis surveiller la qualité de l’eau.','Transforme un problème environnemental en projet avec objectif, action, responsable et indicateur de résultat.',['Première étape ?','Identifier et comprendre la cause du problème.','Pourquoi mesurer les résultats ?','Pour vérifier l’efficacité des actions.']],
    ['Biodiversité et équilibre des écosystèmes','La biodiversité désigne la diversité des êtres vivants et des écosystèmes. Les organismes sont reliés par des relations alimentaires et leur dépendance aux conditions du milieu. La disparition d’une espèce peut modifier plusieurs relations.','Si une espèce prédatrice disparaît, certaines proies peuvent augmenter et modifier la végétation ou les ressources disponibles.','Construis une chaîne alimentaire simple puis explique ce qui pourrait arriver si un maillon disparaissait.',['Que comprend la biodiversité ?','La diversité des êtres vivants, des espèces et des écosystèmes.','Pourquoi une disparition peut-elle avoir plusieurs effets ?','Parce que les organismes sont interdépendants.']]
  ]
};

const subjectMap = {
  'francais-6e': {niveau:'6e', matiereId:'francais', codePrefix:'2026-2027_dpfc_6e_francais_ch'},
  'physique_chimie-6e': {niveau:'6e', matiereId:'physique_chimie', codePrefix:'2026-2027_dpfc_6e_physique_chimie_ch'},
  'svt-6e': {niveau:'6e', matiereId:'svt', codePrefix:'2026-2027_dpfc_6e_svt_ch'}
};

function course(title, lesson, example, exercise) {
  return ['# '+title,'','## 1. Comprendre',lesson,'','## 2. Exemple guidé',example,'','## 3. Méthode','1. Lis attentivement la situation.','2. Repère les informations utiles et le vocabulaire du chapitre.','3. Explique ton raisonnement avec des phrases complètes.','4. Vérifie que ta conclusion répond exactement à la question.','','## 4. Exercice d’application',exercise,'','## 5. À retenir','**Définition → observation ou données → raisonnement → conclusion.**'].join('\n');
}
function quiz(title, q) {
  return q.map((x,i)=>({id:'q'+(i+1),type:'qcm',enonce:x[0],choix:[x[1],x[2],'Aucune des deux','Toutes les réponses'],bonnesReponses:[0],points:1,explication:'La réponse attendue est : '+x[1]+'.'}));
}
function fiche(title, lesson) {
  return ['# Fiche de révision — '+title,'','## Essentiel',lesson,'','## Méthode','Définir les mots importants → expliquer avec ses propres mots → donner un exemple → vérifier sa réponse.','','## Auto-évaluation','□ Je peux définir la notion.','□ Je peux expliquer le mécanisme ou la règle.','□ Je peux donner un exemple.','□ Je peux résoudre une situation nouvelle.'].join('\n');
}

async function findResource(chapitreId,type){
  const s=await db.collection('ca_ressources').where('chapitreId','==',chapitreId).where('type','==',type).limit(10).get();
  return s.empty ? null : s.docs[0];
}
async function main(){
  let updated=0, created=0;
  for(const [key, data] of Object.entries(lessons)){
    const cfg=subjectMap[key];
    for(let i=0;i<data.length;i++){
      const [title,lesson,example,exercise,q]=data[i];
      const code=cfg.codePrefix+String(i+1).padStart(2,'0');
      const s=await db.collection('ca_chapitres').where('code','==',code).limit(1).get();
      if(s.empty){console.log('CHAPITRE_ABSENT',code);continue;}
      const ch=s.docs[0];
      const base={chapitreId:ch.id,niveau:cfg.niveau,matiereId:cfg.matiereId,ecoleId:'',imagesUrls:[],pdfUrl:'',videoYoutubeId:'',enonce:'',solution:'',difficulte:1,ressourceLieeId:'',dureeMinutes:25,examen:false,annee:2026,serie:'',actif:true,ressourceNationale:true,auteur:'sentinel-pedagogie-2026',dateMaj:FieldValue.serverTimestamp()};
      const resources=[
        {type:'cours',titre:'Cours complet — '+title,ordre:1,contenu:course(title,lesson,example,exercise),questions:[]},
        {type:'exercice',titre:'Exercices corrigés — '+title,ordre:2,contenu:'## Série d’exercices\n\n### Exercice 1\n'+exercise+'\n\n### Correction guidée\nCommence par identifier les informations utiles, applique la notion du cours, puis rédige une conclusion complète.\n\n### Exercice 2\nDonne un nouvel exemple lié à ton quotidien et justifie ta réponse en trois phrases.',questions:[]},
        {type:'renforcement',titre:'Renforcement — '+title,ordre:3,contenu:'## Défi progressif\n\nExplique la notion sans regarder le cours, puis invente une situation dans laquelle elle s’applique. Compare ensuite ta réponse avec la fiche de révision.',questions:[]},
        {type:'quiz',titre:'Quiz — '+title,ordre:4,contenu:'Réponds aux questions puis vérifie les explications après correction.',questions:quiz(title,q)},
        {type:'fiche',titre:'Fiche de révision — '+title,ordre:5,contenu:fiche(title,lesson),questions:[]}
      ];
      for(const item of resources){
        const existing=await findResource(ch.id,item.type);
        const payload={...base,...item,dateMaj:FieldValue.serverTimestamp()};
        if(existing){await existing.ref.update(payload);updated++;}else{await db.collection('ca_ressources').add({...payload,dateCreation:FieldValue.serverTimestamp()});created++;}
      }
    }
  }
  await db.collection('ca_parametres').doc('version').set({version:FieldValue.increment(1),anneeScolaire:'2026-2027',derniereRessourceNationale:'cycle1_matieres_generiques_enrichies',dateMaj:FieldValue.serverTimestamp()},{merge:true});
  console.log(JSON.stringify({ok:true,updated,created},null,2));
}
main().catch(e=>{console.error('ENRICH_GENERIC_ERROR');console.error(e&&e.stack?e.stack:e);process.exit(1);});
