const { initializeApp, applicationDefault }=require('firebase-admin/app');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
initializeApp({credential:applicationDefault(),projectId:'sentinel-ci-c7592'});const db=getFirestore();
const L=[
['Lire et comprendre un récit','Identifier situation initiale, événements, personnages, point de vue et schéma narratif.',['Qu’est-ce qu’un narrateur ?','Celui qui raconte l’histoire.'],['Que décrit la situation initiale ?','Le cadre et l’état initial du récit.'],['Pourquoi repérer le point de vue ?','Pour comprendre les informations données au lecteur.']],
['Le texte descriptif','Observer l’organisation d’une description, les expansions du nom et les effets produits.',['Une expansion du nom ?','Un élément qui précise un nom : adjectif, complément du nom ou proposition subordonnée relative.'],['Quel temps est fréquent dans une description ?','L’imparfait.'],['À quoi sert une description ?','À représenter précisément un lieu, un personnage ou un objet.']],
['Poésie et images','Comprendre vers, strophe, rythme, rimes et figures de style courantes.',['Une strophe ?','Un groupe de vers.'],['Une comparaison ?','Un rapprochement explicite avec un outil comme « comme ».'],['Une métaphore ?','Un rapprochement sans outil de comparaison.']],
['Théâtre','Lire une scène en distinguant répliques, didascalies, actes et effets dramatiques.',['Une didascalie ?','Une indication destinée à guider la mise en scène.'],['Une réplique ?','Les paroles prononcées par un personnage.'],['Un dialogue théâtral ?','Un échange de paroles entre personnages.']],
['Argumenter','Identifier thèse, arguments, exemples et connecteurs logiques.',['Une thèse ?','L’idée ou position que l’auteur cherche à défendre.'],['Un argument ?','Une raison utilisée pour soutenir une thèse.'],['Un exemple ?','Un cas concret qui illustre ou appuie un argument.']],
['Classes grammaticales','Reconnaître nom, déterminant, adjectif, pronom, verbe, adverbe, préposition et conjonction.',['Classe de « rapidement » ?','Adverbe.'],['Classe de « ces » ?','Déterminant démonstratif.'],['Classe de « mais » ?','Conjonction de coordination.']],
['Fonctions grammaticales','Identifier sujet, COD, COI, attribut et compléments circonstanciels.',['Dans « Paul lit un livre », COD ?','« un livre ».'],['Dans « Paul semble fatigué », attribut ?','« fatigué ».'],['Comment trouver le sujet ?','En demandant qui est-ce qui ou qu’est-ce qui fait l’action.']],
['Phrase simple et phrase complexe','Compter les propositions et distinguer juxtaposition, coordination et subordination.',['Une phrase complexe ?','Une phrase comportant plusieurs propositions.'],['Deux propositions reliées par « et » ?','Elles sont coordonnées.'],['Deux propositions séparées par une virgule sans mot de liaison ?','Elles sont juxtaposées.']],
['Proposition subordonnée relative','Identifier le pronom relatif, l’antécédent et la proposition relative.',['Dans « le livre que je lis », antécédent ?','« livre ».'],['Pronom relatif de « la fille qui parle » ?','« qui ».'],['Rôle de la relative ?','Préciser un nom ou groupe nominal.']],
['Discours direct et indirect','Transformer des paroles rapportées en tenant compte des pronoms, temps et repères.',['Le discours direct ?','Les paroles sont rapportées telles qu’elles sont prononcées, généralement avec guillemets.'],['Que devient souvent « je » au discours indirect ?','Le pronom s’adapte au point de vue du narrateur.'],['Pourquoi modifier les temps ?','Parce que les repères temporels dépendent de la phrase introductrice.']],
['Accords et orthographe','Maîtriser accords dans le groupe nominal et accord sujet-verbe.',['Accord de « des fleurs rouges » ?','« fleurs » est féminin pluriel et « rouges » s’accorde au féminin pluriel.'],['Que commande le sujet au verbe ?','La personne et le nombre.'],['Dans « les élèves travaillent », sujet ?','« les élèves ».']],
['Conjugaison et vocabulaire','Consolider temps verbaux, valeurs et formation du vocabulaire.',['Valeur fréquente de l’imparfait dans un récit ?','Description, habitude ou action en cours dans le passé.'],['Radical de « impossible » ?','« possible » avec le préfixe « im- ».'],['Un synonyme ?','Un mot de sens proche.']]
];
function quiz(x){return [{id:'q1',type:'qcm',enonce:'Quelle notion est étudiée ?',choix:[x[0],'Une notion sans rapport','Aucune'],bonnesReponses:[0],points:1},{id:'q2',type:'qcm',enonce:x[2][0],choix:[x[2][1],'Réponse contraire','Aucune réponse'],bonnesReponses:[0],points:1},{id:'q3',type:'qcm',enonce:'Quelle démarche aide à comprendre un texte ?',choix:['Relever les indices puis les interpréter','Ignorer le contexte','Deviner sans lire'],bonnesReponses:[0],points:1},{id:'q4',type:'qcm',enonce:'Après une réponse, que faut-il faire ?',choix:['La justifier par le texte ou une règle','Ne pas vérifier','Changer la question'],bonnesReponses:[0],points:1}];}
async function main(){let cc=0,ce=0,rc=0;for(let i=0;i<L.length;i++){const x=L[i],id='4e_francais_ch'+String(i+1).padStart(2,'0'),cr=db.collection('ca_chapitres').doc(id),s=await cr.get();if(!s.exists){await cr.set({code:'2026-2027_dpfc_4e_francais_ch'+String(i+1).padStart(2,'0'),niveau:'4e',matiereId:'francais',anneeScolaire:'2026-2027',programmeVersion:'dpfc',serie:'',theme:i<5?'Lecture et expression':i<10?'Grammaire et syntaxe':'Orthographe, conjugaison et vocabulaire',titre:x[0],description:x[1],ordre:i+1,actif:true,ressourceNationale:true,sourceOfficielle:'DPFC — Programme éducatif et guide d’exécution Français 4e',dateMaj:FieldValue.serverTimestamp()});cc++;}else ce++;const ex=[x[2],x[3],x[4]],docs=[{id:id+'_cours_complet',type:'cours',titre:'Cours complet — '+x[0],ordre:1,contenu:'# '+x[0]+'\n\n## Cours\n'+x[1]+'\n\n## Méthode\nObserver les indices, nommer la notion, justifier avec une règle ou un passage du texte.'},{id:id+'_exercices_corriges',type:'exercice',titre:'Exercices corrigés — '+x[0],ordre:2,contenu:ex.map((e,j)=>'### Exercice '+(j+1)+'\n'+e[0]+'\n\n**Correction :** '+e[1]).join('\n\n'),enonce:ex.map((e,j)=>(j+1)+'. '+e[0]).join('\n'),solution:ex.map((e,j)=>(j+1)+'. '+e[1]).join('\n')},{id:id+'_renforcement',type:'renforcement',titre:'Renforcement — '+x[0],ordre:3,contenu:'Refais les trois exercices sans regarder les corrections.\n\n'+ex.map((e,j)=>(j+1)+'. '+e[0]).join('\n')+'\n\nAuto-évaluation : notion □ méthode □ justification □ correction □'},{id:id+'_quiz',type:'quiz',titre:'Quiz — '+x[0],ordre:4,questions:quiz(x),dureeMinutes:8},{id:id+'_fiche_revision',type:'fiche',titre:'Fiche de révision — '+x[0],ordre:5,contenu:'# Fiche de révision — '+x[0]+'\n\n'+x[1]+'\n\n## Réflexes\n• Lire attentivement.\n• Identifier les indices.\n• Employer le vocabulaire grammatical/littéraire précis.\n• Justifier la réponse.'}];for(const r of docs){const ref=db.collection('ca_ressources').doc(r.id);if((await ref.get()).exists)continue;await ref.set({type:r.type,titre:r.titre,ordre:r.ordre,chapitreId:id,niveau:'4e',matiereId:'francais',ecoleId:'',contenu:r.contenu||'',imagesUrls:[],pdfUrl:'',videoYoutubeId:'',enonce:r.enonce||'',solution:r.solution||'',difficulte:1,ressourceLieeId:'',questions:r.questions||[],dureeMinutes:r.dureeMinutes||0,examen:'',annee:0,serie:'',actif:true,ressourceNationale:true,auteur:'sentinel-francais4e-2026',dateCreation:FieldValue.serverTimestamp(),dateMaj:FieldValue.serverTimestamp()});rc++;}}await db.collection('ca_parametres').doc('version').set({version:FieldValue.increment(1),dateMaj:FieldValue.serverTimestamp(),derniereRessourceNationale:'4e_francais_2026_2027'},{merge:true});console.log(JSON.stringify({ok:true,niveau:'4e',matiere:'francais',lecons:L.length,chapitresCrees:cc,chapitresDejaPresents:ce,ressourcesCreees:rc},null,2));}main().catch(e=>{console.error(e);process.exit(1);});